### ISSUE TITLE
Implement \Serializable and throw exception in EnumerableType::serialize()

### ISSUE THREAD

**Issue by sc0rp10** [antanas-arvasevicius/enumerable-type#3]
Now documentation says `Don't use default php serialize/unserialize for EnumerableType`.
It will be nice if these limitations will be figured out in code, not just documentation.
My proposition:
```php
public function serialize() {
    throw new \RuntimeException(sprintf('Unable to serialize [%s]', static::class));
}

public function unserialize($serialized) {
    throw new \RuntimeException(sprintf('Unable to unserialize [%s]', static::class));
}
```

**Comment by antanas-arvasevicius** [comment]
Hello, thanks for your suggestion, but I feel that this approach is a bit of hack. We are realizing an interface Serializable which says this instances is serializable and then throwing exceptions on serialization attempts.
Personally I don't like that "unserialize" will become a public method of instances. What's the logical reason to have unserialize method in objects?
But I would like to forbid usage of php default serialization.  
Hey, I think `__sleep()` could be used for that.  
By inspecting php code I can see that in serialization they look if "__sleep" exists on object.
https://github.com/php/php-src/blob/1e196110d3e1ef0b67597227dd01a7610d533a6a/ext/standard/var.c#L890  
And if object will have `private function __sleep() {}` it should fail during serialization and also this method won't be visible to users.  
I'll update a library, thanks :)

**Comment by antanas-arvasevicius** [comment]
Lol, private function __sleep() generates only warning... instead of exception will make public and throw runtime there.

**Comment by sc0rp10** [comment]
I agree that Serialilzable looks lika a dirty hack.
Also, I think that some exception with clear message is better than warning. which can be silenced.
